  0%|                                                                                                                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]/home/icl2/anaconda3/lib/python3.10/site-packages/torch/cuda/memory.py:330: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
  0%|                                                                                                                                                                                                                                                                                        | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/icl2/khlee/InstaFlow/code/main_new_algorithm.py", line 302, in <module>
    main()
  File "/home/icl2/khlee/InstaFlow/code/main_new_algorithm.py", line 242, in main
    table.add_data(wandb.Image(original_image), wandb.Image(recon_image), wandb.Image(diff_image), wandb.Image(original_latents_visualized), wandb.Image(recon_latents_visualized), wandb.Image(diff_latents_visualized), error_TOT, error_OTO, error_middle, output_loss, peak_gpu_allocated, inf_time, inv_time, seed, prompt)
  File "/home/icl2/anaconda3/lib/python3.10/site-packages/wandb/data_types.py", line 466, in add_data
    raise ValueError(
ValueError: This table expects 17 columns: ['original_image', 'recon_image', 'diff_image', 'original_latents_visualized', 'recon_latents_visualized', 'diff_latents_visualized', 'error_TOT', 'error_OTO', 'error_middle', 'output_loss', 'dec_inv memory', 'inf_time', 'inv_time', 'seed', 'prompt', 'cocercivity_process', 'cocercivity_inf'], found 15